title: Lorcan McLaren
email: lorcanmclaren@gmail.com
author: Lorcan McLaren
description:
url: https://lorcanmclaren.com/

collections:
  topics:
    output: true

defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


show_social_icons: true
github_username: LorcanMcLaren

sass:
  sass_dir: assets/css

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag